import { CLOUDINARY_BASE_URL, pitchtember_url } from './const';

export const EVENTS_DATA = [
  {
    id: 'orientation-2023',
    title: 'Orientation Session 2023',
    tagline: 'Welcoming New Innovators & Startup Founders',
    category: 'Workshop',
    status: 'Past',
    date: '21/09/2023',
    startDate: '2023-09-21',
    endDate: null,
    time: '04:00 PM - 06:30 PM IST',
    venue: 'CV Raman Hall',
    mode: 'In-Person',
    image: `${CLOUDINARY_BASE_URL}/v1782890669/orientation_fdo0yp.jpg`,
    url: '/timeline',
    description:
      'Orientation session for incoming student founders and innovators introducing incubation center facilities, Tinkering Lab access, and funding guidance.',
    highlights: [
      'Introduction to Incubation Center support pillars.',
      'Interactive Q&A with student coordinators and faculty mentors.',
      'Overview of prototype seed grants and lab hardware facilities.',
    ],
    speakers: [
      { name: 'Prof. Bharat Gupta', role: 'Professor-In-Charge, IC NITP' },
    ],
    eligibility: 'All NIT Patna students and aspiring student entrepreneurs.',
    sponsors: [
      {
        id: 'mic-gov',
        name: "Ministry of Education's Innovation Cell",
        shortName: 'MIC India',
        tier: 'Chief Sponsor',
        isHighlighted: true,
        logoKey: 'mic',
        website: 'https://mic.gov.in/',
        description: 'Government of India initiative establishing Institution\'s Innovation Councils (IIC) and seed funding networks across premier technical institutes.',
        perk: 'Incubation Grant Framework',
      },
      {
        id: 'tinkering-lab',
        name: 'NIT Patna Tinkering Lab',
        shortName: 'Tinkering Lab',
        tier: 'Prototyping Partner',
        isHighlighted: true,
        logoKey: 'tinkering',
        website: 'https://incubationcenter.nitp.ac.in',
        description: 'State-of-the-art hardware prototyping facility equipped with 3D printers, laser cutters, PCB printers, and IoT testing workstations.',
        perk: 'Free Hardware Lab Access',
      },
      {
        id: 'ieee-nitp',
        name: 'IEEE Student Branch NIT Patna',
        shortName: 'IEEE NITP',
        tier: 'Academic Partner',
        isHighlighted: false,
        logoKey: 'ieee',
        website: 'https://nitp.ac.in',
        description: 'Premier student technical community conducting hands-on hardware workshops, hackathons, and technical paper mentorship.',
        perk: 'Technical Mentorship',
      },
    ],
  },
  {
    id: 'pitchtember-2023',
    title: 'PitchTember 2023',
    tagline: 'Flagship National Startup Pitching Competition',
    category: 'Competition',
    status: 'Past',
    date: '24/11/2023 to 18/12/2023',
    startDate: '2023-11-24',
    endDate: '2023-12-18',
    time: '10:00 AM - 06:00 PM IST',
    venue: 'CV Raman Hall',
    mode: 'Hybrid',
    image: `${CLOUDINARY_BASE_URL}/v1782890669/pitchtember_ax6djs.jpg`,
    url: pitchtember_url,
    description:
      'The annual flagship startup pitching event at NIT Patna bringing together promising early-stage founders, angel investor panels, and enterprise mentors.',
    highlights: [
      'National startup pitch presentations before investor panel.',
      'Incubation seed support and mentorship awards.',
      'Keynotes on fundraising strategy and MVP validation.',
    ],
    speakers: [
      { name: 'Antesh Anand', role: 'Founder, Brand Medix' },
    ],
    eligibility: 'Open to student founders and early-stage startup teams.',
    sponsors: [
      {
        id: 'startup-bihar',
        name: 'Department of Industries, Startup Bihar',
        shortName: 'Startup Bihar',
        tier: 'Title Sponsor',
        isHighlighted: true,
        logoKey: 'startup_bihar',
        website: 'https://startup.bihar.gov.in/',
        description: 'Official Government of Bihar startup promotion policy offering up to ₹10 Lakhs seed grant funding, incubation support, and fiscal incentives.',
        perk: '₹10 Lakhs Seed Grant Pool',
      },
      {
        id: 'aws-startups',
        name: 'AWS for Startups',
        shortName: 'AWS Startups',
        tier: 'Powered By',
        isHighlighted: true,
        logoKey: 'aws',
        website: 'https://aws.amazon.com/startups/',
        description: 'Global cloud infrastructure partner providing up to $10,000 in AWS Activate credits, 1-on-1 architecture reviews, and 24/7 technical support.',
        perk: '$10,000 AWS Cloud Credits',
      },
      {
        id: 'meity-hub',
        name: 'MeitY Startup Hub (MSH)',
        shortName: 'MeitY Hub',
        tier: 'Ecosystem Partner',
        isHighlighted: false,
        logoKey: 'meity',
        website: 'https://meitystartuphub.in/',
        description: 'Ministry of Electronics & Information Technology platform nurturing tech incubators, patent support, and deep-tech seed acceleration.',
        perk: 'National Incubator Access',
      },
      {
        id: 'github-edu',
        name: 'GitHub Education',
        shortName: 'GitHub',
        tier: 'Developer Partner',
        isHighlighted: false,
        logoKey: 'github',
        website: 'https://education.github.com/',
        description: 'Empowering student developer teams with GitHub Student Developer Packs, Enterprise cloud seats, and automated CI/CD workflows.',
        perk: 'Student Developer Pack',
      },
      {
        id: 'google-cloud',
        name: 'Google Cloud for Startups',
        shortName: 'Google Cloud',
        tier: 'Cloud Partner',
        isHighlighted: false,
        logoKey: 'gcp',
        website: 'https://cloud.google.com/startup',
        description: 'Providing AI & machine learning infrastructure credits, Google Workspace tools, and expert technical mentorship for pitching finalists.',
        perk: 'Google Cloud & AI Credits',
      },
    ],
  },
  {
    id: 'stock-market-simulation-2024',
    title: 'Stock Market Simulation',
    tagline: 'Real-Time Financial Markets & Investment Challenge',
    category: 'Competition',
    status: 'Past',
    date: '09/02/2024',
    startDate: '2024-02-09',
    endDate: null,
    time: '02:00 PM - 06:00 PM IST',
    venue: 'Online',
    mode: 'Online',
    image: `${CLOUDINARY_BASE_URL}/v1782890671/sms_a5537x.jpg`,
    url: '/timeline',
    description:
      'An interactive online virtual trading challenge giving participants hands-on experience in portfolio management, risk evaluation, and equity analysis.',
    highlights: [
      'Real-time virtual stock market simulation environment.',
      'Cash prizes and certificates for top performing portfolio managers.',
      'Expert session on equity valuation and risk management.',
    ],
    speakers: [
      { name: 'Dr. Amitesh Kumar', role: 'Faculty Advisor' },
    ],
    eligibility: 'Open to all students interested in finance, trading, and markets.',
    sponsors: [
      {
        id: 'zerodha-varsity',
        name: 'Zerodha Varsity',
        shortName: 'Zerodha',
        tier: 'Title Sponsor',
        isHighlighted: true,
        logoKey: 'zerodha',
        website: 'https://zerodha.com/varsity/',
        description: 'India\'s largest financial education ecosystem offering free self-paced learning, virtual market simulation tools, and certification.',
        perk: 'Trading Credits & Certification',
      },
      {
        id: 'groww',
        name: 'Groww Financial Services',
        shortName: 'Groww',
        tier: 'Platform Partner',
        isHighlighted: true,
        logoKey: 'groww',
        website: 'https://groww.in/',
        description: 'Leading fintech platform sponsoring cash rewards for top virtual portfolio traders and conducting stock analysis workshops.',
        perk: 'Cash Prize Sponsorship',
      },
      {
        id: 'bse-ipf',
        name: 'BSE Investor Protection Fund',
        shortName: 'BSE India',
        tier: 'Knowledge Partner',
        isHighlighted: false,
        logoKey: 'bse',
        website: 'https://www.bseindia.com/',
        description: 'Bombay Stock Exchange initiative fostering financial literacy, market ethics, and equity investment awareness for young investors.',
        perk: 'Financial Literacy Seminars',
      },
    ],
  },
];
